<!-- 모임목적 인서트문 -->
insert into gms_purpose(name) values ("문화/예술/음악");
insert into gms_purpose(name) values ("교육/자기개발");
insert into gms_purpose(name) values ("육아/가족/반려동물");
insert into gms_purpose(name) values ("인문/과학");
insert into gms_purpose(name) values ("스포츠/레져");
insert into gms_purpose(name) values ("도서/독서");
insert into gms_purpose(name) values ("정치/사회/역사");
insert into gms_purpose(name) values ("건강/의료");
insert into gms_purpose(name) values ("영화/애니메이션");
insert into gms_purpose(name) values ("경제/금융/재테크");
insert into gms_purpose(name) values ("인테리어/조경/DIY");
insert into gms_purpose(name) values ("게임");
insert into gms_purpose(name) values ("여행/취미/여가");
insert into gms_purpose(name) values ("공연/전시");
insert into gms_purpose(name) values ("디자인");
insert into gms_purpose(name) values ("TV/미디어");
insert into gms_purpose(name) values ("패션/뷰티");
insert into gms_purpose(name) values ("외국어");
insert into gms_purpose(name) values ("IT/컴퓨터");
insert into gms_purpose(name) values ("쇼핑/생활/푸드");
insert into gms_purpose(name) values ("기부/봉사");
insert into gms_purpose(name) values ("창업/경영");

-- 지역 데이터

INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '중구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '용산구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '성동구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '광진구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '동대문구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '중랑구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '성북구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '강북구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '도봉구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '노원구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '은평구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '서대문구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '마포구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '양천구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '강서구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '구로구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '금천구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '영등포구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '동작구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '관악구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '서초구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '강남구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '송파구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('서울특별시', '강동구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('부산광역시', '중구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('부산광역시', '서구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('부산광역시', '동구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('부산광역시', '영도구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('부산광역시', '부산진구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('부산광역시', '동래구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('부산광역시', '남구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('부산광역시', '북구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('부산광역시', '해운대구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('부산광역시', '사하구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('부산광역시', '금정구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('부산광역시', '강서구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('부산광역시', '연제구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('부산광역시', '수영구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('부산광역시', '사상구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('부산광역시', '기장군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('대구광역시', '중구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('대구광역시', '동구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('대구광역시', '서구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('대구광역시', '남구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('대구광역시', '북구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('대구광역시', '수성구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('대구광역시', '달서구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('대구광역시', '달성군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('인천광역시', '중구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('인천광역시', '동구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('인천광역시', '미추홀구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('인천광역시', '연수구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('인천광역시', '남동구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('인천광역시', '부평구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('인천광역시', '계양구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('인천광역시', '서구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('인천광역시', '강화군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('인천광역시', '옹진군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('인천광역시', '동구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('인천광역시', '서구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('인천광역시', '남구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('인천광역시', '북구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('인천광역시', '광산구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('대전광역시', '소계');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('대전광역시', '동구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('대전광역시', '중구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('대전광역시', '서구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('대전광역시', '유성구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('대전광역시', '대덕구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('울산광역시', '중구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('울산광역시', '남구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('울산광역시', '동구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('울산광역시', '북구');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('울산광역시', '울주군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('세종특별자치시', '세종특별자치시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '수원시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '성남시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '고양시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '용인시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '부천시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '안산시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '안양시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '남양주시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '화성시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '평택시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '의정부시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '시흥시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '파주시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '광명시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '김포시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '군포시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '광주시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '이천시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '양주시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '오산시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '구리시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '안성시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '포천시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '의왕시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '하남시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '여주시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '양평군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '동두천시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '과천시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '가평군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경기도', '연천군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('강원도', '춘천시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('강원도', '원주시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('강원도', '강릉시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('강원도', '동해시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('강원도', '태백시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('강원도', '속초시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('강원도', '삼척시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('강원도', '홍천군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('강원도', '횡성군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('강원도', '영월군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('강원도', '평창군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('강원도', '정선군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('강원도', '철원군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('강원도', '화천군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('강원도', '양구군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('강원도', '인제군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('강원도', '고성군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('강원도', '양양군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청북도', '청주시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청북도', '충주시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청북도', '제천시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청북도', '보은군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청북도', '옥천군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청북도', '영동군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청북도', '진천군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청북도', '괴산군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청북도', '음성군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청북도', '단양군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청북도', '증평군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청남도', '천안시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청남도', '공주시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청남도', '보령시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청남도', '아산시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청남도', '서산시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청남도', '논산시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청남도', '계룡시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청남도', '당진시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청남도', '금산군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청남도', '부여군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청남도', '서천군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청남도', '청양군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청남도', '홍성군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청남도', '예산군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('충청남도', '태안군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라북도', '전주시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라북도', '군산시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라북도', '익산시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라북도', '정읍시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라북도', '남원시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라북도', '김제시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라북도', '완주군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라북도', '진안군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라북도', '무주군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라북도', '장수군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라북도', '임실군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라북도', '순창군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라북도', '고창군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라북도', '부안군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '목포시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '여수시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '순천시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '나주시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '광양시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '담양군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '곡성군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '구례군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '고흥군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '보성군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '화순군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '장흥군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '강진군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '해남군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '영암군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '무안군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '함평군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '영광군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '장성군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '완도군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '진도군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('전라남도', '신안군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '소계');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '포항시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '경주시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '김천시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '안동시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '구미시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '영주시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '영천시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '상주시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '문경시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '경산시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '군위군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '의성군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '청송군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '영양군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '영덕군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '청도군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '고령군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '성주군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '칠곡군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '예천군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '봉화군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '울진군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상북도', '울릉군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상남도', '소계');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상남도', '창원시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상남도', '진주시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상남도', '통영시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상남도', '사천시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상남도', '김해시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상남도', '밀양시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상남도', '거제시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상남도', '양산시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상남도', '의령군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상남도', '함안군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상남도', '창녕군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상남도', '고성군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상남도', '남해군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상남도', '하동군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상남도', '산청군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상남도', '함양군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상남도', '거창군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('경상남도', '합천군');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('제주특별자치도', '제주시');
INSERT INTO gms_activelocal (name_si, name_gu) VALUES ('제주특별자치도', '서귀포시');
